In [1]:
import pandas as pd
df=pd.read_csv('air_poll.csv')

In [2]:
df.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Bihar,Patna,"Govt. High School Shikarpur, Patna - BSPCB",24-08-2026 11:00:00,25.592539,85.227158,SO2,12.0,13.0,13.0
1,India,Bihar,Patna,"Muradpur, Patna - BSPCB",24-08-2026 11:00:00,25.619651,85.147382,PM2.5,40.0,53.0,45.0
2,India,Bihar,Patna,"Muradpur, Patna - BSPCB",24-08-2026 11:00:00,25.619651,85.147382,OZONE,5.0,43.0,16.0
3,India,Bihar,Patna,"Samanpura, Patna - BSPCB",24-08-2026 11:00:00,25.596727,85.085624,PM2.5,25.0,239.0,90.0
4,India,Bihar,Patna,"Samanpura, Patna - BSPCB",24-08-2026 11:00:00,25.596727,85.085624,NH3,4.0,5.0,5.0

In [3]:
df.dtypes

country           object
state             object
city              object
station           object
last_update       object
latitude         float64
longitude        float64
pollutant_id      object
pollutant_min    float64
pollutant_max    float64
pollutant_avg    float64
dtype: object

In [4]:
df.shape

(3472, 11)

In [5]:
df['last_update']=pd.to_datetime(df['last_update'],format="%d-%m-%Y %H:%M:%S").dt.date

In [7]:
df.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Bihar,Patna,"Govt. High School Shikarpur, Patna - BSPCB",2026-08-24,25.592539,85.227158,SO2,12.0,13.0,13.0
1,India,Bihar,Patna,"Muradpur, Patna - BSPCB",2026-08-24,25.619651,85.147382,PM2.5,40.0,53.0,45.0
2,India,Bihar,Patna,"Muradpur, Patna - BSPCB",2026-08-24,25.619651,85.147382,OZONE,5.0,43.0,16.0
3,India,Bihar,Patna,"Samanpura, Patna - BSPCB",2026-08-24,25.596727,85.085624,PM2.5,25.0,239.0,90.0
4,India,Bihar,Patna,"Samanpura, Patna - BSPCB",2026-08-24,25.596727,85.085624,NH3,4.0,5.0,5.0

In [8]:
df.isnull().sum()

country            0
state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    323
pollutant_max    323
pollutant_avg    323
dtype: int64

In [9]:
df[df.isna().any(axis=1)]

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
13,India,Assam,Nalbari,"Bata Chowk, Nalbari - PCBA",2026-08-24,26.446912,91.439057,NH3,NaN,NaN,NaN
25,India,Bihar,Munger,"Town Hall, Munger - BSPCB",2026-08-24,25.376776,86.471523,PM2.5,NaN,NaN,NaN
34,India,Bihar,Patna,"Rajbansi Nagar, Patna - BSPCB",2026-08-24,25.599486,85.113666,PM2.5,NaN,NaN,NaN
59,India,Assam,Guwahati,"Pan Bazaar, Guwahati - PCBA",2026-08-24,26.187500,91.744194,PM2.5,NaN,NaN,NaN
65,India,Bihar,Bhagalpur,"DM Office_Kachari Chowk, Bhagalpur - BSPCB",2026-08-24,25.251013,86.989001,PM2.5,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3365,India,Tamil Nadu,Coimbatore,"SIDCO Kurichi, Coimbatore - TNPCB",2026-08-24,10.942451,76.978996,PM2.5,NaN,NaN,NaN
3367,India,Tamil Nadu,Cuddalore,"Kudikadu, Cuddalore - TNPCB",2026-08-24,11.682990,79.753210,NO2,NaN,NaN,NaN
3368,India,Tamil Nadu,Thoothukudi,"Meelavittan, Thoothukudi - TNPCB",2026-08-24,8.816428,78.099039,PM2.5,NaN,NaN,NaN
3379,India,West Bengal,Durgapur,"PCBL Residential Complex, Durgapur - WBPCB",2026-08-24,23.508764,87.354440,OZONE,NaN,NaN,NaN
3439,India,Uttar Pradesh,Modinagar,"SRM University, Modinagar - UPPCB",2026-08-24,28.798171,77.540243,PM10,NaN,NaN,NaN

In [10]:
df['data_status'] = df[['pollutant_min', 'pollutant_max', 'pollutant_avg']].notna().all(axis=1).map({
    True: 'Available',
    False: 'Missing'
})

In [11]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg,data_status
0,India,Bihar,Patna,"Govt. High School Shikarpur, Patna - BSPCB",2026-08-24,25.592539,85.227158,SO2,12.0,13.0,13.0,Available
1,India,Bihar,Patna,"Muradpur, Patna - BSPCB",2026-08-24,25.619651,85.147382,PM2.5,40.0,53.0,45.0,Available
2,India,Bihar,Patna,"Muradpur, Patna - BSPCB",2026-08-24,25.619651,85.147382,OZONE,5.0,43.0,16.0,Available
3,India,Bihar,Patna,"Samanpura, Patna - BSPCB",2026-08-24,25.596727,85.085624,PM2.5,25.0,239.0,90.0,Available
4,India,Bihar,Patna,"Samanpura, Patna - BSPCB",2026-08-24,25.596727,85.085624,NH3,4.0,5.0,5.0,Available

In [14]:
df['data_status'].value_counts()

data_status
Available    3149
Missing       323
Name: count, dtype: int64

In [15]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Prafulsql4266@localhost:3306/air_poll")

# Upload DataFrame to MySQL
df.to_sql(
    "air_poll",
    con=engine,
    if_exists="replace",
    index=False
)

3472